### ISSUE TITLE
Installation fails on macOS 12 (Monterey) due to Net::SSLeay complaining about LibreSSL 2.8.3

### ISSUE THREAD

**Issue by Pierre-Andre** [maelvls/homebrew-amc#68]
Bonjour,

brew install fails with the following output. May be an issue libreSSL/openSSL ?
Thanks for the formula and all the work you have done on it :)

Bien cordialement

```
:brew install maelvls/amc/auto-multiple-choice       
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Pango-1.227.tar.g
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/697dfba960e5ba6ece01c4091cd30c04d737c68767b9fd1301930a4a3ba963ab--Pango-1.227.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-Depends-
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/dcc96c015237086825bdc8c3c7298b9f33e3baa15177eba78b9f2cd4b3f805ac--ExtUtils-Depends-0.405.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-1.327.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/23fcf994a8a74f94d0791b426eee7961be69778223edc11888a4fec6b69db9bf--Glib-1.327.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-PkgConfi
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/eb3a93c9b38aaf5bfe3eb8dc0c21839aab129ff06ba2943fd52c2d1f32078e49--ExtUtils-PkgConfig-1.16.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Cairo-1.106.tar.g
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/02c3ad376d38dc8d8b294b3413756ca15a367141284412bc0c3c5c6221ebe90f--Cairo-1.106.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.63
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/db98b993af756ec2769e045d17e910b46acdbda5d60ebf489e0e6e1710744a79--Archive-Zip-1.63.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModul
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/21c071761300e2fb90c292c4bb3348ae030c2b68d13d9c22977f9dbc4bad3242--Test-MockModule-v0.170.0.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/bfd9108e895391377668b5400495b0f105f5e3d8a5a5a7a2a2cca27cf25cbc2b--Module-Build-0.4224.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/C/CH/CHROMATIC/SUPER-1.2014
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/2ab6048e048563fc64ef0e2d61c7269e581ae35231a4caf99df5fcf9439cf82a--SUPER-1.20141117.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RG/RGARCIA/Sub-Identify-0
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/c7d08c111286b6777323935b333b6a14215fea3fd45edd6c0097d3bada2256f8--Sub-Identify-0.14.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GARU/Clone-0.39.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/e6728ddd73d945cc6bd4656f8cb4f97b1f9122aec5c793345c62967ea30590e2--Clone-0.39.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/a92a8e02e8a5c422600292003d0eaa6333eaa8db99d1a06bd5507331e02de58d--DBD-SQLite-1.58.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.641.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/f502a2876b8ca0e8032deb47a57ae7dd79cfdc5e55f9e567c90a881b557d80c7--DBI-1.641.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-MD5-2.55.t
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/baac8bccca3319200ab6056c001123bc35e6c57ce8c39d86656ebd8818bb821d--Digest-MD5-2.55.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MIME-1.946.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/519521e8839a2875ccfc757df174c26e52a3f7d2343d92e483ab1171e59f1727--Email-MIME-1.946.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Simple-2.21
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/ba241d46ec9fd0834767c9855c208d6bb780dd1c2589dc671674aa17311f5ab1--Email-Simple-2.216.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Date-Format
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/62d0155aecb6ffeca6ba43d966e085e85f7f6fef7b7476096009b28c989264b3--Email-Date-Format-1.005.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Module-Runtime-
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/7c5c96d89db1b9861d18c44840c988b6770a7484d6ac6ff027d455cfa25a2dc7--Module-Runtime-0.016.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MessageID-1
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/2762eddc6d520dfe21acaa5cf723c534da4e0068a4e2844a8b19588228072826--Email-MessageID-1.406.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MA/MARKOV/MIME-Types-2.17
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/70980f98cb47c588b1f2ac4777d961be4e6b9ddd11dc1b8ccf4fddfc539b46a8--MIME-Types-2.17.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PA/PALI/Email-Address-XS-
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/96e524a045faaa754c4f9952c089b73e0389fa219e2085e5019d58860a88cf32--Email-Address-XS-1.04.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MIME-Encodi
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/bb1b77d50d64bf1fa90dba3f34b1581170099617a3d195eddc18e8280687c8b7--Email-MIME-Encodings-1.315.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/cda2d3e0714f4a985bbf78868124724269ac99eb4761a08e63890ca74ae0b2d0--Capture-Tiny-0.48.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-MIME-Conten
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/3f54004514ca5c69c7b8104dc0249cc022cfcbb5498e24f82f6451a3172f4aea--Email-MIME-ContentType-1.022.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Sender-1.30
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/927275748d568f518a259f57b5782a60e5de3fa07ac242bcf0239250a9a7c7d9--Email-Sender-1.300031.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Sub-Exporter-0.98
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/3e2bbef449e534b2570cb204504465c089738656df52c8cdbf404c7083dfbc1d--Sub-Exporter-0.987.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Params-Util-1.07
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/6b3b3b5524bae0b0da3aa0e296be79b4fdea56993dedcab112284f3004d581ee--Params-Util-1.07.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Data-OptList-0.11
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/5f76d262c54ba1eab012e8c5f27530510ae4be45e17095b90632b308e622bc95--Data-OptList-0.110.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Sub-Install-0.928
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/7cddbc2134fa7bde381bf4a4a512c54757db13fb62329ed4114c4d3d1cb03b27--Sub-Install-0.928.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MA/MATEU/MooX-Types-Moose
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/fdf05a4d22b7232f8621becfdfd4e8e05f9f60437c808f5b521e696c61324292--MooX-Types-MooseLike-0.29.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.014.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/4ae945c22d637c8a5df0f507e84fd706b48330c907e6f3573d255568f65c1fb9--Test-Fatal-0.014.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.ta
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/102436356836b7053d86fc59bf14a0df4626b5f7516a37e327173294d1b28f59--Try-Tiny-0.30.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/Moo-2.003004.tar
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/3dd146de1f8cad6fc31459ef1c69f40903b602249438b29861166dc825f63ee7--Moo-2.003004.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.0000
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9e03db5b9df2c1be90d02a3caa275e9697b8e92035b8397366482078a1ec95ae--Role-Tiny-2.000006.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.0050
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/8083e3a2485a339719a19572c07d307b59f0ed8f329c94857a28c2e552746116--Sub-Quote-2.005001.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Mod
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/e303fc979855c2cd011eab12d0374d8fa8cf15caed2d20a190f2381a8ba361df--Class-Method-Modifiers-2.12.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-Require
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/1c848f66439adc1c5afb8f369f97723860f683c29f2e53577c36e4edb1a4876d--Test-Requires-0.10.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/Devel-GlobalDest
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/38efbbc77710cbdcf27b87e8d6ee17eda36aa2956d8c1ba045824ec0059aa86e--Devel-GlobalDestruction-0.14.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/F/FR/FREW/Sub-Exporter-Prog
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9f3e9ba1f01bfc574c028c2ed928bdcf22b30604cb89304b09330ad841b6636c--Sub-Exporter-Progressive-0.001013.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Abstract-3.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/a8a18592e5ebc09e5c46aa4edeeaeae2c0602c69c707d802e920fc22e8d66540--Email-Abstract-3.008.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Simple-2.21
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/ba241d46ec9fd0834767c9855c208d6bb780dd1c2589dc671674aa17311f5ab1--Email-Simple-2.216.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/MRO-Compat-0.13.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/b63f21608c4a4e1daf799ac3225a4f361dff100d87476208de66bd7e330265b6--MRO-Compat-0.13.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/S/SI/SIMONW/Module-Pluggabl
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/c7097c3ce378bff3450e5d449602b22be053a7b41b96ae1b0f0688b07497f7d2--Module-Pluggable-5.2.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Throwable-0.20001
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/a7d463f935849a7d1dc6cf0a29fbc64b48c924f9bbc5953c7cad65dacbd7f944--Throwable-0.200013.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTra
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/234f7eac4e549ef3ca1c8e22eb9933f4405aa9a363ee3c00a51a65ef9c2ab4df--Devel-StackTrace-2.03.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Address-1.9
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/46ce3b35ea4595215c71da0cf4e8f8d9251f32cd2d4fc092f91221c4c5c58a05--Email-Address-1.909.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/K/KI/KIMRYAN/File-BaseDir-0
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/45733dc1b201f0838555628633ece06dc3322b3eee635a1f2793d3401ef1c1b3--File-BaseDir-0.08.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MI/MICHIELB/File-MimeInfo
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/e93fef6283016fb42313765757cc1bc19d68191d28e488443cf97fe2b5d3d9a1--File-MimeInfo-0.29.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PJ/PJF/IPC-System-Simple-
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/786c33b5df4d8b7c1fdc97325dc6961fbfa71255a7187fade56dddc35fb0dea5--IPC-System-Simple-1.25.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/0436311236fd9fdb1678db3669149d5e114a33200a28bc6b75f073ed2d7a9c4c--File-Which-1.22.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MI/MICHIELB/File-DesktopE
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9a54f1b6f8e91b06dabb3149e088b64f134bbcebc4c7c3aa7d9bd9c230a7dc7d--File-DesktopEntry-0.22.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/594f9085239d3098a4f0377b69450a9e4f51a4b9403b15bb33add2d08d3a1dd6--URI-1.74.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/af2f07430dffb11ec56a51365504eedbd5e40d6773069d73d20b80d8a7ebd262--Test-Needs-0.002005.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Glib-Object-Intro
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/1fce058c00f606ccfa7cd2f7996371c47280460c628593220576e9466bc4bc27--Glib-Object-Introspection-0.045.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Gtk3-0.034.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/083e59750b7f47a3c023f0ce46f7a26bcbd123d508e61a030edde1427efab684--Gtk3-0.034.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/X/XA/XAOC/Cairo-GObject-1.0
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/c131c689bd6128e6d1e4247d66543fa27248b1a5022badfc23ddb9fe2fb6727d--Cairo-GObject-1.004.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PV/PVANDRY/gettext-1.07.t
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/f3c614d72d3b3eafe5b6d9284baa8e580d2fc773cad0da3c70c050c135e0dff8--gettext-1.07.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-Load-Con
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9e3db20da3d2e8f13af0b47527003011261561b545a77cbf6096ccc56b7efadc--Module-Load-Conditional-0.68.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/J/JM/JMGDOC/OpenOffice-OODo
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/52835797058c505c815df06cef41ce12a42c7af13fecc2e91da67221bddaae30--OpenOffice-OODoc-2.125.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-Twig-3.52.ta
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/80cc3008d2e752b206db017e151cdef269aebe22aa3f37465b666c3454689aff--XML-Twig-3.52.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/3948f45448ce280a3858f863934ea711a56695d7a55e179df695b809722c0767--XML-Parser-2.44.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.35
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/bf7e50216cabe616003103ee4c1361f4cde0620039ad91cc8bc45817d2d00dda--libwww-perl-6.35.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/M/MA/MALLEN/Test-RequiresIn
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/118f95cb4eaf425e19bf25c936d92a13753b869312db3b5c8d9a034b3e6c79a1--Test-RequiresInternet-0.05.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/J/JC/JCRISTY/PerlMagick-6.8
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/bfc353deb6923b9c675dd125b0661b42ed001ffd62957f769b8bcdaa11607889--PerlMagick-6.89-1.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-1.97
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/7b7f9e97d762a30736d8bf9b3d3f261a030729bd46edd4cd952ce242c9e4f468--Text-CSV-1.97.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-Simple-2.25
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/be03cbf89eb80eeb901d63c50a32809a99480f16009b3b5041c62d87a3e1798c--XML-Simple-2.25.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-1.00.ta
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/6efc7b85cc289861d404b1bdffe7994293ed5a82da28dbe4c9f54fa1abab55ab--XML-SAX-1.00.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-Namespace
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/d303969bf80b9225c7f35508da928c6f1fd997d09374098a6d11915f43b35faf--XML-NamespaceSupport-1.12.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/2db533b2d2eefaca47c747e65e1f0205375312f8f8c77da12f34ec78d6b830e8--XML-SAX-Base-1.09.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/B/BJ/BJOERN/XML-SAX-Expat-0
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/115ef97f6dd55287c0504a139e3ef2f51d8a5bc9f0940ee1f559d16e8945457b--XML-SAX-Expat-0.51.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/02a203b0d9be1021d06c2ae500cf56b8099f816dc0f35f256fd3705a758c55cc--HTTP-Message-6.18.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/LWP-MediaTypes-6.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/5094ea9b41400cb8c8ed378463120ccd680dba01082bbf5b0ceecc6fbb0f871c--LWP-MediaTypes-6.02.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/Encode-Locale-1.0
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/b8572ed2f8bf52e4bc44975d16da43f80fc697a8d65c50b8aca13ca74889fb06--Encode-Locale-1.05.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/74e4a29abebb57daa95485044f9ae3db49514e7cd911e0df42f4fba7cef8c206--IO-HTML-1.001.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/594f9085239d3098a4f0377b69450a9e4f51a4b9403b15bb33add2d08d3a1dd6--URI-1.74.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Date-6.02.ta
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/536a113b563cca6a38e30e5f03f3791c11ca91ff4572551bddc989260ab3f200--HTTP-Date-6.02.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/File-Listing-6.04
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/24cb24e39aa8394ce9bad66465c47ec0fe7762d7a6c90d35333e601f288c19c6--File-Listing-6.04.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Daemon-6.01.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/20e11e29a331aed0f16e73014f71284ff133d6aaf1388e539d71a21dd9a6da02--HTTP-Daemon-6.01.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/0fb8add5cd1b3b1dea43455d8180153d119269afba9eaf019b1366503a7ddfa2--HTML-Tagset-3.20.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/dce6edfed97d78bbc4b1b1ae27b692ee524f96b8075d5bf3ab859a6b6d2bbd2c--HTTP-Cookies-6.04.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/WWW-RobotRules-6.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/6e07f35ac438084e8574203c7c7e30d85022c8366fdb911998dc3555821009ab--WWW-RobotRules-6.02.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Negotiate-6.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/6159129f3ebd7583d1d10ea8a080cf17cd65fdc4f3b33191a14cca811b23574e--HTTP-Negotiate-6.01.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.18.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9abf251a2f632292a240975185cece4f411908f5f84f767fdadc7f1e14632ba2--Net-HTTP-6.18.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/J/JO/JOSEPHW/XML-Writer-0.6
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/4def5cc5b424847cadb14aaf48caedf559e64575800ca46be9140c662e71fe86--XML-Writer-0.625.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/S/SB/SBECK/Locale-Codes-3.5
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/5bd48c00b8bcdc426d1c619ba654a31a4866aef49469db47648b0766ccfdfc9e--Locale-Codes-3.58.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/S/SB/SBECK/Locale-Codes-3.5
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/5bd48c00b8bcdc426d1c619ba654a31a4866aef49469db47648b0766ccfdfc9e--Locale-Codes-3.58.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/79e6560b598888a70a25912106081280582baabe77b0275cfe6046bc7786e04b--IO-Socket-SSL-2.071.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.90
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/30daa20b851db369f6adf1838abe12833da14bfbec7a0028a397cec05956d944--Net-SSLeay-1.90.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/A/AB/ABH/Mozilla-CA-2020052
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/163e8caaaf8d8d6baa967dee47464ba23d14133d321361f647ca91ce0e963a34--Mozilla-CA-20200520.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/G/GB/GBARR/Authen-SASL-2.16
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/9c375c8f76fe9d997565eaf05d5d7c206b05a8233349fb80366a27aed7edd59f--Authen-SASL-2.16.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/A/AR/ARODLAND/Digest-HMAC-1
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/7b28b3d80493af0023be01b1671cc5ff85bb66f265ea4173b0d158df2ceea666--Digest-HMAC-1.04.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/Module-Install-1
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/ec5ed381525d0ea227f67eef20c301454d29ef505ba66b5727efc5d579a6f000--Module-Install-1.19.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/Module-ScanDep
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/230696cef08d2b1080233976bb13610036d070189cd3201445535227896acb81--Module-ScanDeps-1.31.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/File-Remove-1.
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/cd54e4e08b91c0a64aae66c2728938235a7ed1c5896cde810199e700add52582--File-Remove-1.60.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.73.t
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/8d3f1f5c15f1ef2a1d5f0aa90417f08744a511cd51aa11aad22a5e63f56f0e28--YAML-Tiny-1.73.tar.gz
==> Downloading https://gitlab.com/jojo_boulix/auto-multiple-choice/uploads/3262
Already downloaded: /Users/johndoe/Library/Caches/Homebrew/downloads/a82ffdfd8fb60d2f30a07ea655eda22dbb14eb4359da8cf43de2e1143141e109--auto-multiple-choice_1.5.0_dist.tar.gz
==> Installing auto-multiple-choice from maelvls/amc
==> make AMCCONF=brew PREFIX=/opt/homebrew/Cellar/auto-multiple-choice/1.5.0 LIB
==> make install_doc AMCCONF=brew PREFIX=/opt/homebrew/Cellar/auto-multiple-choi
==> make install_nodoc AMCCONF=brew PREFIX=/opt/homebrew/Cellar/auto-multiple-ch
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.
Last 15 lines from /Users/johndoe/Library/Logs/Homebrew/auto-multiple-choice/31.perl:

perl
Makefile.PL
INSTALL_BASE=/opt/homebrew/Cellar/auto-multiple-choice/1.5.0/libexec
INSTALLMAN1DIR=none
INSTALLMAN3DIR=none

Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] n
*** Found LibreSSL-2.8.3 installed in /usr
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Checking if your kit is complete...
Looks good
WARNING: /opt/homebrew/opt/perl/bin/perl is loading libcrypto in an unsafe way

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/maelvls/homebrew-amc/issues

```

**Comment by maelvls** [comment]
Hi! I noticed this failure yesterday. I think I need to force the use of
openssl 1.1 since the latest libressl is not compatible with ssleay.

I’ll try to have this issue fixed today.



Le mer. 1 déc. 2021 à 18:54, Pierre-Andre ***@***.***> a
écrit :

**Comment by PasLafon** [comment]
Hello,
Having exactly the same issue with MacBookPro M1 macOS Big Sur 11.6.1.
I have tried to install openssl 1.1. with brew install openssl@1.1 and adding in my .bash_profile :

# If you need to have openssl@1.1 first in your PATH
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"

# For compilers to find openssl@3 you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

#For pkg-config to find openssl@3 you may need to set:
export OPENSSL_PREFIX=/opt/homebrew/opt/openssl@1.1

But this do not solve the problem ..

**Comment by Pierre-Andre** [comment]
As I am a newbie in Mac OS I forgot to mention that it occurs on an ARM M1...

**Comment by Pierre-Andre** [comment]
Another mac OS 12 but intel now: on this one it lacks the right version of libffi : with this version of brew on macOS 12 it comes with libffi.8.dylib:

```
Can't load '/usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/darwin-thread-multi-2level/auto/Glib/Object/Introspection/Introspection.bundle' for module Glib::Object::Introspection: dlopen(/usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/darwin-thread-multi-2level/auto/Glib/Object/Introspection/Introspection.bundle, 0x0001): Library not loaded: /usr/local/opt/libffi/lib/libffi.7.dylib
  Referenced from: /usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/darwin-thread-multi-2level/auto/Glib/Object/Introspection/Introspection.bundle
  Reason: tried: '/usr/local/opt/libffi/lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file), '/usr/local/Cellar/libffi/3.4.2/lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file) at /usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/XSLoader.pm line 96.
 at /usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/Gtk3.pm line 48.
Compilation failed in require at /usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/Gtk3.pm line 48.
BEGIN failed--compilation aborted at /usr/local/Cellar/auto-multiple-choice/1.5.0/libexec/lib/perl5/Gtk3.pm line 48.
Compilation failed in require at /usr/local/Cellar/auto-multiple-choice/1.5.0/lib/AMC/perl/AMC-gui.pl line 26.
BEGIN failed--compilation aborted at /usr/local/Cellar/auto-multiple-choice/1.5.0/lib/AMC/perl/AMC-gui.pl line 26
```

A basic soft link on the new version circumvent the problem:

```
cd /usr/local/opt/libffi/lib ;
ln -s libffi.dylib libffi.7.dylib
```
while waiting for the new version ;-)

**Comment by maelvls** [comment]
I fixed the issue with Net::SSLeay. Let me know if that works.

Not sure why libffi.7.dylib can’t be loaded; was it a fresh install or did you upgrade to macOS 12 and noticed this issue?

**Comment by Pierre-Andre** [comment]
On that mac I have 
1. uninstalled brew using the shell script provided by the brew team
    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"`
2. updated MAC OS using the GUI provided by apple
3. reinstalled brew (using the script)
4. brew install auto-multiple-choice and mactex

I can't be sure that the uninstall step have done its job as requested. The installation is in /usr/local for the intel and in /opt for the arm M1 and this is weird for me (is that a sign that an old piece of the previous installation of brew still remain somewhere on the intel or may be this is normal ?)

**Comment by Pierre-Andre** [comment]
thus the installation of auto-multiple-choice leads to the installation of libffi but the version is now version 8 and the link is done on the version 7 (may be instead of linking to a specific version a generic one will be sufficient).

Thanks for all your work by the way !

**Comment by maelvls** [comment]
Is this still an issue for you?

**Comment by Pierre-Andre** [comment]
1) For ARM M1:
I have tried today but it is still failing (on a further step: gobject-introspection)

`==> Installing auto-multiple-choice from maelvls/amc
==> Installing dependencies for maelvls/amc/auto-multiple-choice: amc-gobject-introspection
==> Installing maelvls/amc/auto-multiple-choice dependency: amc-gobject-int
==> Patching
==> Applying a7be304478b25271166cd92d110f251a8742d16b.diff
patching file girepository/gitypelib.c
Hunk #1 succeeded at 2261 (offset 2 lines).
patching file meson.build
Hunk #1 succeeded at 157 with fuzz 1 (offset 33 lines).
patching file meson_options.txt
==> meson --prefix=/opt/homebrew/Cellar/amc-gobject-introspection/1.70.0-16 --li
Last 15 lines from /Users/foouser/Library/Logs/Homebrew/amc-gobject-introspection/01.meson:
Configuring message.py using configuration
Configuring msvccompiler.py using configuration
Configuring pkgconfig.py using configuration
Configuring shlibs.py using configuration
Configuring scannermain.py using configuration
Configuring sectionparser.py using configuration
Configuring sourcescanner.py using configuration
Configuring testcodegen.py using configuration
Configuring transformer.py using configuration
Configuring utils.py using configuration
Configuring xmlwriter.py using configuration

../giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.

A full log can be found at /private/tmp/amc-gobject-introspection-20220116-72709-177yn3z/gobject-introspection-1.70.0-16-g366a886b/build/meson-logs/meson-log.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/maelvls/homebrew-amc/issues
`
2) For intel 
not tested but I can do it if you need to be sure

Thanks and happy new year

**Comment by Pierre-Andre** [comment]
oups a technical problem on this GUI and the ticket was closed

**Comment by maelvls** [comment]
I don't have an M1 Mac at hand at the moment, and cannot reproduce the issue unfortunately. 😞

**Comment by Pierre-Andre** [comment]
[brew  formula for gobject-introspection](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gobject-introspection.rb)
includes your patch 
```
  # Fix library search path on non-/usr/local installs (e.g. Apple Silicon)
  # See: https://github.com/Homebrew/homebrew-core/issues/75020
  #      https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/273
  patch do
    url "https://gitlab.gnome.org/tschoonj/gobject-introspection/-/commit/a7be304478b25271166cd92d110f251a8742d16b.diff"
    sha256 "740c9fba499b1491689b0b1216f9e693e5cb35c9a8565df4314341122ce12f81"
  end
```
and also other patches. One seems to address the docstring problem:
```
  # Upstream patch for doctemplates error
  # Review for removal at version bump
  # See: https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/414
  patch do
    url "https://gitlab.gnome.org/GNOME/gobject-introspection/-/commit/effb1e09dee263cdac4ec593e8caf316e6f01fe2.diff"
    sha256 "e0f4932f230a26563c0948b83d3ec347b7ecd195503a6d4f1519a276a8022b95"
  end
```
But as the new [brew  formula for gobject-introspection](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gobject-introspection.rb) seems to be a little bit further may I suggest to remove the call to your gobject-introspection formula and to try with the "main stream" one ?
I can test an updated formula this WE (the M1 mac is not mine…)

**Comment by mcaruel** [comment]
Hi Pierre-Andre,
Sorry I'm not familiar with the kind of workaround you seem to be suggesting. I can try to do some tests but I need guidance on the procedures. Should I copy-paste some code in my terminal ? which one ?

**Comment by Pierre-Andre** [comment]
I can propose the following workaround (instead of waiting an update of the formula by Maël Valais). I suppose that you have attempted to install amc:
```
brew install maelvls/amc/auto-multiple-choice
```
and it did not work.  
To make it works you can try the following steps
1. open a Terminal (in Applications/Utilitaires)
2. locate the maelvls tap and change to this directory and list all files
    ```
    cd $(brew --repo)
    cd Library/Taps/maelvls/homebrew-amc
    ls
    ```
3. In this directory there is the ruby file with all the directive to install auto-multiple-choice: `auto-multiple-choice.rb`. We want to replace all reference to `amc-gobject-introspection` (a local formula) by `gobject-introspection` (the brew formula).  
 To do this, you have to open this file (named `auto-multiple-choice.rb`) and change inside all reference to `amc-gobject-introspection` by `gobject-introspection` using a texteditor. Save the file.
4. install the new formula
```
brew install maelvls/amc/auto-multiple-choice
```

Well this is a workaround that works on the ARM M1 mac that I have borrowed… 

Thanks to Mael Valais who have done all the work (remember that all the mistakes are from me)

**Comment by mcaruel** [comment]
It worked 🎉 ! Thanks a lot !

**Comment by maelvls** [comment]
Hi,

I opened #76 with @Pierre-Andre's suggestion to use `gobject-introspection` instead of using the outdated `amc-gobject-introspection`. I will get it merged today.

**Comment by maelvls** [comment]
@mcaruel @Pierre-Andre Can you try installing auto-multiple-choice now? The formula now points to the upstream `gobject-introspection`.

**Comment by Pierre-Andre** [comment]
It works thanks !
